// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: job.sql

package database

import (
	"context"
	"database/sql"
)

const addJob = `-- name: AddJob :exec
INSERT INTO jobs (id, created_at, position, url, company_id, location, source_id)
VALUES (?, CURRENT_TIMESTAMP, ?, ?, ?, ?,  ?)
`

type AddJobParams struct {
	ID        string
	Position  string
	Url       string
	CompanyID string
	Location  sql.NullString
	SourceID  int64
}

func (q *Queries) AddJob(ctx context.Context, arg AddJobParams) error {
	_, err := q.db.ExecContext(ctx, addJob,
		arg.ID,
		arg.Position,
		arg.Url,
		arg.CompanyID,
		arg.Location,
		arg.SourceID,
	)
	return err
}
