// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: job_postings.sql

package database

import (
	"context"
	"time"
)

const createJobPosting = `-- name: CreateJobPosting :exec
INSERT OR IGNORE INTO job_postings (created_at, updated_at, last_posted, position, url, company_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateJobPostingParams struct {
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LastPosted time.Time
	Position   string
	Url        string
	CompanyID  string
}

func (q *Queries) CreateJobPosting(ctx context.Context, arg CreateJobPostingParams) error {
	_, err := q.db.ExecContext(ctx, createJobPosting,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastPosted,
		arg.Position,
		arg.Url,
		arg.CompanyID,
	)
	return err
}
