// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type Company struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	Avatar    sql.NullString
}

type JobPosting struct {
	ID           string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastPosted   time.Time
	Position     string
	Url          string
	CompanyID    string
	LocationType int64
	Location     sql.NullString
}

type User struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserJobPosting struct {
	CreatedAt    time.Time
	UserID       int64
	JobPostingID string
	Hidden       bool
}
