// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: scrape_keywords.sql

package database

import (
	"context"
)

const addKeywordToScrape = `-- name: AddKeywordToScrape :exec
INSERT INTO scrape_keywords (created_at, updated_at, scrape_id, keyword)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?, ?)
`

type AddKeywordToScrapeParams struct {
	ScrapeID int64
	Keyword  string
}

func (q *Queries) AddKeywordToScrape(ctx context.Context, arg AddKeywordToScrapeParams) error {
	_, err := q.db.ExecContext(ctx, addKeywordToScrape, arg.ScrapeID, arg.Keyword)
	return err
}
