// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: scrape_position_blacklisted_words.sql

package database

import (
	"context"
)

const addPositionBlacklistedWordToScrape = `-- name: AddPositionBlacklistedWordToScrape :exec
INSERT INTO scrape_position_blacklisted_words (created_at, updated_at, scrape_id, blacklisted_word)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?, ?)
`

type AddPositionBlacklistedWordToScrapeParams struct {
	ScrapeID        int64
	BlacklistedWord string
}

func (q *Queries) AddPositionBlacklistedWordToScrape(ctx context.Context, arg AddPositionBlacklistedWordToScrapeParams) error {
	_, err := q.db.ExecContext(ctx, addPositionBlacklistedWordToScrape, arg.ScrapeID, arg.BlacklistedWord)
	return err
}
