// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_job_postings.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createUserJobPosting = `-- name: CreateUserJobPosting :exec
INSERT INTO user_job_postings (created_at, user_id, position, company_id)
VALUES (CURRENT_TIMESTAMP, ?, ?, ?)
`

type CreateUserJobPostingParams struct {
	UserID    int64
	Position  string
	CompanyID string
}

func (q *Queries) CreateUserJobPosting(ctx context.Context, arg CreateUserJobPostingParams) error {
	_, err := q.db.ExecContext(ctx, createUserJobPosting, arg.UserID, arg.Position, arg.CompanyID)
	return err
}

const getUserJobPostings = `-- name: GetUserJobPostings :many
SELECT job_postings.position, job_postings.url as job_posting_url, companies.name as company_name, last_posted, companies.avatar as company_avatar 
FROM user_job_postings
JOIN companies on job_postings.company_id = companies.id
JOIN job_postings on user_job_postings.position = job_postings.position AND user_job_postings.company_id = job_postings.company_id
WHERE user_job_postings.user_id = ?
ORDER BY job_postings.last_posted DESC
`

type GetUserJobPostingsRow struct {
	Position      string
	JobPostingUrl string
	CompanyName   string
	LastPosted    time.Time
	CompanyAvatar sql.NullString
}

func (q *Queries) GetUserJobPostings(ctx context.Context, userID int64) ([]GetUserJobPostingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserJobPostings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserJobPostingsRow
	for rows.Next() {
		var i GetUserJobPostingsRow
		if err := rows.Scan(
			&i.Position,
			&i.JobPostingUrl,
			&i.CompanyName,
			&i.LastPosted,
			&i.CompanyAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
