services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TZ=${TZ}
  scraper:
    build:
      context: .
      dockerfile: docker/scraper/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PROXY_HOSTNAME=${PROXY_HOSTNAME}
      - PROXY_PORT=${PROXY_PORT}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - TZ=${TZ}
      - LOCAL_DB=${LOCAL_DB}
