services:
  jobsummoner:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PROXY_HOSTNAME=${PROXY_HOSTNAME}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - DEBUG=${DEBUG}
      - SCRAPE_ON_START=${SCRAPE_ON_START}
    volumes: 
      - db:/app/db

volumes:
  db: