// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlitedb

import (
	"database/sql"
	"time"
)

type Company struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Name      string
	Url       string
	Avatar    sql.NullString
	SourceID  string
}

type Job struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
	LastPosted time.Time
	Position   string
	Url        string
	CompanyID  string
	Location   sql.NullString
	SourceID   string
}

type Scrape struct {
	ID        int64
	SourceID  string
	CreatedAt time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type User struct {
	ID             int64
	Name           string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      sql.NullTime
}
