package linkedin

import (
	"bytes"
	"fmt"
	"log/slog"
	"testing"
	"time"

	"github.com/m1yon/jobsummoner/internal/models"
	"github.com/stretchr/testify/assert"
)

func TestLinkedInScraper(t *testing.T) {
	t.Run("file reader - scrape and paginates job listings correctly with 2 pages", func(t *testing.T) {
		fileReader := NewFileLinkedInReader("./test-helpers/li-job-listings-%v.html")
		logger := slog.New(slog.NewTextHandler(nil, nil))
		scraper := NewLinkedInJobScraper(fileReader, logger)

		got, errs := scraper.ScrapeJobs(time.Now().Add(-30 * time.Minute))
		want := []models.Job{
			{Position: "Senior Software Engineer", Location: "New York City Metropolitan Area", URL: "https://www.linkedin.com/jobs/view/senior-software-engineer-at-goliath-partners-3941197019?position=1&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=TtFssv3yCaLnbvL4n7pGqw%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "goliath-partners-inc", CompanyName: "Goliath Partners", CompanyAvatar: "https://media.licdn.com/dms/image/C4E0BAQEGxoU_V_HCSw/company-logo_100_100/0/1675096738538/goliath_partners_inc_logo?e=1725494400&v=beta&t=510KsQO8Mz1Sj_F3qxetiyblMOlbQobQENe8gkxvBk0", CompanyURL: "https://www.linkedin.com/company/goliath-partners-inc?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Full Stack Engineer", Location: "New York City Metropolitan Area", URL: "https://www.linkedin.com/jobs/view/full-stack-engineer-at-goliath-partners-3941199093?position=2&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=qbBBmbaU%2FGecHsilZU6rPg%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "goliath-partners-inc", CompanyName: "Goliath Partners", CompanyAvatar: "https://media.licdn.com/dms/image/C4E0BAQEGxoU_V_HCSw/company-logo_100_100/0/1675096738538/goliath_partners_inc_logo?e=1725494400&v=beta&t=510KsQO8Mz1Sj_F3qxetiyblMOlbQobQENe8gkxvBk0", CompanyURL: "https://www.linkedin.com/company/goliath-partners-inc?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Application Developer", Location: "Tempe, AZ", URL: "https://www.linkedin.com/jobs/view/application-developer-at-proliance-consulting-3938872094?position=3&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=yp1wpeQB6Yl5V0C%2FQp1Rsw%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "proliance-consulting", CompanyName: "Proliance Consulting", CompanyAvatar: "https://media.licdn.com/dms/image/C560BAQFugask4NG0LQ/company-logo_100_100/0/1657048404925/proliance_consulting_logo?e=1725494400&v=beta&t=mc2EAAV0DnDfmDLvLS5gI6Sa8foubI5MJeW0b5M6MEQ", CompanyURL: "https://www.linkedin.com/company/proliance-consulting?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "DevOps Engineer", Location: "Portland, Maine Metropolitan Area", URL: "https://www.linkedin.com/jobs/view/devops-engineer-at-firstpro-inc-3941423455?position=4&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=uFqmQan2fgvaePCw9yJi%2Bw%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "firstpro", CompanyName: "firstPRO, Inc", CompanyAvatar: "https://media.licdn.com/dms/image/C560BAQERIg4JrLCchQ/company-logo_100_100/0/1631309275036?e=1725494400&v=beta&t=BAyXnGBpEDdLFIIk3upjqtHK49QHWbIm47PNGffNa_w", CompanyURL: "https://www.linkedin.com/company/firstpro?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Software Developer 4", Location: "Seattle, WA", URL: "https://www.linkedin.com/jobs/view/software-developer-4-at-oracle-3926234960?position=5&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=V9okmTSo%2FMAajAtqw9viYQ%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Senior Software Engineer - Full Stack", Location: "New York City Metropolitan Area", URL: "https://www.linkedin.com/jobs/view/senior-software-engineer-full-stack-at-titan-3904725366?position=6&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=sL3X%2BQ7k7ebAi9hQ2MzRzw%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "titan-invest", CompanyName: "Titan", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQGWjUnr1ibbvw/company-logo_100_100/0/1689171878095/titan_invest_logo?e=1725494400&v=beta&t=2texljHk4i40uP1RMf-_J6akJJpZfzS9GkPkzauIuPg", CompanyURL: "https://www.linkedin.com/company/titan-invest?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Software Developer 4", Location: "Austin, TX", URL: "https://www.linkedin.com/jobs/view/software-developer-4-at-oracle-3926236707?position=7&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=DzcGOX9aApHdauzctJsjGg%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Software Developer 4", Location: "Redwood City, CA", URL: "https://www.linkedin.com/jobs/view/software-developer-4-at-oracle-3914083553?position=8&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=grmTG%2FuW6DmSaBwEmGKlBQ%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Senior Software Engineer", Location: "Greater Seattle Area", URL: "https://www.linkedin.com/jobs/view/senior-software-engineer-at-rentspree-3938840276?position=9&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=dkiwVGJIEqnYXvSqgvjO8w%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "rentspree", CompanyName: "RentSpree", CompanyAvatar: "https://media.licdn.com/dms/image/D560BAQHOY6BViU03Kg/company-logo_200_200/0/1717280161612/rentspree_logo?e=1725494400&v=beta&t=-mkOnVQWSHKY9g_MhfV8EDQp_Iqt3L_fiEvqpLY4Rzg", CompanyURL: "https://www.linkedin.com/company/rentspree?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Analyst, Developer Specialty 3", Location: "St Paul, MN", URL: "https://www.linkedin.com/jobs/view/analyst-developer-specialty-3-at-tekwissen-%C2%AE-3938822375?position=10&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=cq1o%2Bo56V3Fdpe038vGwug%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "tekwissen", CompanyName: "TekWissen ®", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQGSbWad5HaJPA/company-logo_100_100/0/1689252430843?e=1725494400&v=beta&t=mldHyfLdjESkA8GNznq-M8e0xJCYv4SYzwfUpm-DpIo", CompanyURL: "https://www.linkedin.com/company/tekwissen?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Senior Principal Engineer - Relocation to Australia", Location: "San Francisco, CA", URL: "https://www.linkedin.com/jobs/view/senior-principal-engineer-relocation-to-australia-at-rokt-3905316034?position=1&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=b%2BQG0mQCaIcp0cHeoz5bTQ%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "rokt", CompanyName: "Rokt", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQE7AmEYtqhs9g/company-logo_100_100/0/1706546290679/rokt_logo?e=1725494400&v=beta&t=4YAa-1OdxQR7cjqRSqPQ9shQpkAsISJTH8Y-bOV1jRs", CompanyURL: "https://www.linkedin.com/company/rokt?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Principal Software Engineer/Sr Principal Software Engineer", Location: "Portland, OR", URL: "https://www.linkedin.com/jobs/view/principal-software-engineer-sr-principal-software-engineer-at-oracle-3911661146?position=2&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=bfNqZnkoWYbjj6bnZS47Tw%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Principal Software Engineer/Sr Principal Software Engineer", Location: "Los Angeles, CA", URL: "https://www.linkedin.com/jobs/view/principal-software-engineer-sr-principal-software-engineer-at-oracle-3911662017?position=3&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=Y%2F9rLjlZm8z8F0NfkPlUIg%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Software Development Manager", Location: "Seattle, WA", URL: "https://www.linkedin.com/jobs/view/software-development-manager-at-oracle-3900536996?position=4&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=kjOrd%2F6ZadeHijvsY1vfIg%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Software Development Senior Manager", Location: "Pleasanton, CA", URL: "https://www.linkedin.com/jobs/view/software-development-senior-manager-at-oracle-3919395308?position=5&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=CDB4Sem7WIv%2BkGAF4DPkHQ%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Principal Software Engineer/Sr Principal Software Engineer", Location: "Austin, TX", URL: "https://www.linkedin.com/jobs/view/principal-software-engineer-sr-principal-software-engineer-at-oracle-3911660279?position=6&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=F7zX0LB%2ByVaZ9IufjIAFiQ%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Senior Software Developer - Data Center Infrastructure Team", Location: "Seattle, WA", URL: "https://www.linkedin.com/jobs/view/senior-software-developer-data-center-infrastructure-team-at-oracle-3900542100?position=7&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=fWzqEG9OjDymYMdpTrT5zA%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Software Development Senior Manager", Location: "Redwood City, CA", URL: "https://www.linkedin.com/jobs/view/software-development-senior-manager-at-oracle-3921687498?position=8&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=hZQ%2B%2B3rtpKibl1ZmT9V4zQ%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Staff Machine Learning Engineer - Seattle", Location: "Seattle, WA", URL: "https://www.linkedin.com/jobs/view/staff-machine-learning-engineer-seattle-at-rokt-3905393698?position=9&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=792eL8NsCwvBl2h%2FjoxGQA%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "rokt", CompanyName: "Rokt", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQE7AmEYtqhs9g/company-logo_100_100/0/1706546290679/rokt_logo?e=1725494400&v=beta&t=4YAa-1OdxQR7cjqRSqPQ9shQpkAsISJTH8Y-bOV1jRs", CompanyURL: "https://www.linkedin.com/company/rokt?trk=public_jobs_jserp-result_job-search-card-subtitle"},
		}

		assert.Equal(t, want, got)
		assert.Equal(t, 0, len(errs))
	})

	t.Run("http reader - scrape and paginates job listings correctly with 2 pages", func(t *testing.T) {
		stubClient := NewStubClient()
		logger := slog.New(slog.NewTextHandler(nil, nil))
		httpReader := NewHttpLinkedInReader(LinkedInReaderConfig{
			Keywords: []string{"Software Engineer", "Manager"},
			Location: "United States",
		}, stubClient, logger)
		scraper := NewLinkedInJobScraper(httpReader, logger)

		got, errs := scraper.ScrapeJobs(time.Now().Add(-30 * time.Minute))
		want := []models.Job{
			{Position: "Senior Software Engineer", Location: "New York City Metropolitan Area", URL: "https://www.linkedin.com/jobs/view/senior-software-engineer-at-goliath-partners-3941197019?position=1&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=TtFssv3yCaLnbvL4n7pGqw%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "goliath-partners-inc", CompanyName: "Goliath Partners", CompanyAvatar: "https://media.licdn.com/dms/image/C4E0BAQEGxoU_V_HCSw/company-logo_100_100/0/1675096738538/goliath_partners_inc_logo?e=1725494400&v=beta&t=510KsQO8Mz1Sj_F3qxetiyblMOlbQobQENe8gkxvBk0", CompanyURL: "https://www.linkedin.com/company/goliath-partners-inc?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Full Stack Engineer", Location: "New York City Metropolitan Area", URL: "https://www.linkedin.com/jobs/view/full-stack-engineer-at-goliath-partners-3941199093?position=2&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=qbBBmbaU%2FGecHsilZU6rPg%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "goliath-partners-inc", CompanyName: "Goliath Partners", CompanyAvatar: "https://media.licdn.com/dms/image/C4E0BAQEGxoU_V_HCSw/company-logo_100_100/0/1675096738538/goliath_partners_inc_logo?e=1725494400&v=beta&t=510KsQO8Mz1Sj_F3qxetiyblMOlbQobQENe8gkxvBk0", CompanyURL: "https://www.linkedin.com/company/goliath-partners-inc?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Application Developer", Location: "Tempe, AZ", URL: "https://www.linkedin.com/jobs/view/application-developer-at-proliance-consulting-3938872094?position=3&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=yp1wpeQB6Yl5V0C%2FQp1Rsw%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "proliance-consulting", CompanyName: "Proliance Consulting", CompanyAvatar: "https://media.licdn.com/dms/image/C560BAQFugask4NG0LQ/company-logo_100_100/0/1657048404925/proliance_consulting_logo?e=1725494400&v=beta&t=mc2EAAV0DnDfmDLvLS5gI6Sa8foubI5MJeW0b5M6MEQ", CompanyURL: "https://www.linkedin.com/company/proliance-consulting?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "DevOps Engineer", Location: "Portland, Maine Metropolitan Area", URL: "https://www.linkedin.com/jobs/view/devops-engineer-at-firstpro-inc-3941423455?position=4&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=uFqmQan2fgvaePCw9yJi%2Bw%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "firstpro", CompanyName: "firstPRO, Inc", CompanyAvatar: "https://media.licdn.com/dms/image/C560BAQERIg4JrLCchQ/company-logo_100_100/0/1631309275036?e=1725494400&v=beta&t=BAyXnGBpEDdLFIIk3upjqtHK49QHWbIm47PNGffNa_w", CompanyURL: "https://www.linkedin.com/company/firstpro?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Software Developer 4", Location: "Seattle, WA", URL: "https://www.linkedin.com/jobs/view/software-developer-4-at-oracle-3926234960?position=5&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=V9okmTSo%2FMAajAtqw9viYQ%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Senior Software Engineer - Full Stack", Location: "New York City Metropolitan Area", URL: "https://www.linkedin.com/jobs/view/senior-software-engineer-full-stack-at-titan-3904725366?position=6&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=sL3X%2BQ7k7ebAi9hQ2MzRzw%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "titan-invest", CompanyName: "Titan", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQGWjUnr1ibbvw/company-logo_100_100/0/1689171878095/titan_invest_logo?e=1725494400&v=beta&t=2texljHk4i40uP1RMf-_J6akJJpZfzS9GkPkzauIuPg", CompanyURL: "https://www.linkedin.com/company/titan-invest?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Software Developer 4", Location: "Austin, TX", URL: "https://www.linkedin.com/jobs/view/software-developer-4-at-oracle-3926236707?position=7&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=DzcGOX9aApHdauzctJsjGg%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Software Developer 4", Location: "Redwood City, CA", URL: "https://www.linkedin.com/jobs/view/software-developer-4-at-oracle-3914083553?position=8&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=grmTG%2FuW6DmSaBwEmGKlBQ%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Senior Software Engineer", Location: "Greater Seattle Area", URL: "https://www.linkedin.com/jobs/view/senior-software-engineer-at-rentspree-3938840276?position=9&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=dkiwVGJIEqnYXvSqgvjO8w%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "rentspree", CompanyName: "RentSpree", CompanyAvatar: "https://media.licdn.com/dms/image/D560BAQHOY6BViU03Kg/company-logo_200_200/0/1717280161612/rentspree_logo?e=1725494400&v=beta&t=-mkOnVQWSHKY9g_MhfV8EDQp_Iqt3L_fiEvqpLY4Rzg", CompanyURL: "https://www.linkedin.com/company/rentspree?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Analyst, Developer Specialty 3", Location: "St Paul, MN", URL: "https://www.linkedin.com/jobs/view/analyst-developer-specialty-3-at-tekwissen-%C2%AE-3938822375?position=10&pageNum=0&refId=QN9Xe6fr3eBaRYE4EMYCIg%3D%3D&trackingId=cq1o%2Bo56V3Fdpe038vGwug%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "tekwissen", CompanyName: "TekWissen ®", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQGSbWad5HaJPA/company-logo_100_100/0/1689252430843?e=1725494400&v=beta&t=mldHyfLdjESkA8GNznq-M8e0xJCYv4SYzwfUpm-DpIo", CompanyURL: "https://www.linkedin.com/company/tekwissen?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Senior Principal Engineer - Relocation to Australia", Location: "San Francisco, CA", URL: "https://www.linkedin.com/jobs/view/senior-principal-engineer-relocation-to-australia-at-rokt-3905316034?position=1&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=b%2BQG0mQCaIcp0cHeoz5bTQ%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "rokt", CompanyName: "Rokt", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQE7AmEYtqhs9g/company-logo_100_100/0/1706546290679/rokt_logo?e=1725494400&v=beta&t=4YAa-1OdxQR7cjqRSqPQ9shQpkAsISJTH8Y-bOV1jRs", CompanyURL: "https://www.linkedin.com/company/rokt?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Principal Software Engineer/Sr Principal Software Engineer", Location: "Portland, OR", URL: "https://www.linkedin.com/jobs/view/principal-software-engineer-sr-principal-software-engineer-at-oracle-3911661146?position=2&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=bfNqZnkoWYbjj6bnZS47Tw%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Principal Software Engineer/Sr Principal Software Engineer", Location: "Los Angeles, CA", URL: "https://www.linkedin.com/jobs/view/principal-software-engineer-sr-principal-software-engineer-at-oracle-3911662017?position=3&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=Y%2F9rLjlZm8z8F0NfkPlUIg%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Software Development Manager", Location: "Seattle, WA", URL: "https://www.linkedin.com/jobs/view/software-development-manager-at-oracle-3900536996?position=4&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=kjOrd%2F6ZadeHijvsY1vfIg%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Software Development Senior Manager", Location: "Pleasanton, CA", URL: "https://www.linkedin.com/jobs/view/software-development-senior-manager-at-oracle-3919395308?position=5&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=CDB4Sem7WIv%2BkGAF4DPkHQ%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Principal Software Engineer/Sr Principal Software Engineer", Location: "Austin, TX", URL: "https://www.linkedin.com/jobs/view/principal-software-engineer-sr-principal-software-engineer-at-oracle-3911660279?position=6&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=F7zX0LB%2ByVaZ9IufjIAFiQ%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Senior Software Developer - Data Center Infrastructure Team", Location: "Seattle, WA", URL: "https://www.linkedin.com/jobs/view/senior-software-developer-data-center-infrastructure-team-at-oracle-3900542100?position=7&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=fWzqEG9OjDymYMdpTrT5zA%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Software Development Senior Manager", Location: "Redwood City, CA", URL: "https://www.linkedin.com/jobs/view/software-development-senior-manager-at-oracle-3921687498?position=8&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=hZQ%2B%2B3rtpKibl1ZmT9V4zQ%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "oracle", CompanyName: "Oracle", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQHYCgYovUuPtQ/company-logo_100_100/0/1665755678957/oracle_logo?e=1725494400&v=beta&t=0ei2rLETdcAfhJFLid323HzN2fXoaKAuzBcWU6cntvU", CompanyURL: "https://www.linkedin.com/company/oracle?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Staff Machine Learning Engineer - Seattle", Location: "Seattle, WA", URL: "https://www.linkedin.com/jobs/view/staff-machine-learning-engineer-seattle-at-rokt-3905393698?position=9&pageNum=2&refId=O7f5RZQjEgD2Ze4PH0mAuQ%3D%3D&trackingId=792eL8NsCwvBl2h%2FjoxGQA%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "rokt", CompanyName: "Rokt", CompanyAvatar: "https://media.licdn.com/dms/image/D4E0BAQE7AmEYtqhs9g/company-logo_100_100/0/1706546290679/rokt_logo?e=1725494400&v=beta&t=4YAa-1OdxQR7cjqRSqPQ9shQpkAsISJTH8Y-bOV1jRs", CompanyURL: "https://www.linkedin.com/company/rokt?trk=public_jobs_jserp-result_job-search-card-subtitle"},
		}

		assert.Equal(t, want, got)
		assert.Equal(t, 0, len(errs))
	})

	t.Run("handles invalid company URLs", func(t *testing.T) {
		mockReader := NewFileLinkedInReader("./test-helpers/li-job-listings_bad-company-url-%v.html")
		logBufferSpy := new(bytes.Buffer)
		logger := slog.New(slog.NewTextHandler(logBufferSpy, nil))
		scraper := NewLinkedInJobScraper(mockReader, logger)

		got, errs := scraper.ScrapeJobs(time.Now().Add(-30 * time.Minute))
		want := []models.Job{
			{Position: "Software Engineer II (Frontend) - Seller Experience", Location: "Los Angeles, CA", URL: "https://www.linkedin.com/jobs/view/software-engineer-ii-frontend-seller-experience-at-stubhub-3916280897?position=2&pageNum=0&refId=fsDMYm%2BoJB2zdtWm%2FhnZ3g%3D%3D&trackingId=dbosG%2Ftu2ZxD8zDrXnrTWw%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "stubhub", CompanyName: "StubHub", CompanyAvatar: "https://media.licdn.com/dms/image/C560BAQEeUqY1MzhaLw/company-logo_100_100/0/1655126776940/stubhub_logo?e=1724889600&v=beta&t=DiahoEBnLyp-sHgVPKEWZv2-ANhZzr9bGzkqibzYtSY", CompanyURL: "https://www.linkedin.com/company/stubhub?trk=public_jobs_jserp-result_job-search-card-subtitle"},
			{Position: "Senior Frontend Developer", Location: "South San Francisco, CA", URL: "https://www.linkedin.com/jobs/view/senior-frontend-developer-at-trilogy-international-3936896077?position=3&pageNum=0&refId=fsDMYm%2BoJB2zdtWm%2FhnZ3g%3D%3D&trackingId=YzFScrnDUB9kJlZ%2FHtqdiQ%3D%3D&trk=public_jobs_jserp-result_search-card", SourceID: "linkedin", CompanyID: "trilogy-international-ltd", CompanyName: "Trilogy International", CompanyAvatar: "https://media.licdn.com/dms/image/C4E0BAQHTr9nVUzrwhA/company-logo_100_100/0/1656664781720/trilogy_international_ltd_logo?e=1724889600&v=beta&t=krum0mLymbeGqVQxNjVuYSQ8qss8irSE1vEwODfX5BE", CompanyURL: "https://www.linkedin.com/company/trilogy-international-ltd?trk=public_jobs_jserp-result_job-search-card-subtitle"},
		}

		assert.Equal(t, want, got)
		assert.Equal(t, 0, len(errs))
		assert.Contains(t, logBufferSpy.String(), fmt.Sprintf(errMalformedCompanyLink, "fda&=+!-//"))
	})
}
