name: Production Deploy
on:
  push:
    branches:
      - v2
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  static_checks:
    uses: m1yon/jobsummoner/.github/workflows/static-checks.yaml@v2
  deploy:
    needs: [static_checks]
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Migrate Turso DB
        run: make migrate-remote-up
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Deploy to Fly
        run: make build-deploy-all
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
