name: Fly Deploy
on:
  push:
    branches:
      - v2
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: make build-deploy-all
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
