name: Static Checks

on:
  push:
    branches:
      - "!v2"
  workflow_call:

jobs:
  code:
    name: Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.22.2"

      - run: go version

      - name: Run tests
        run: make test-ci

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
